export interface iLanguages {
  home:string,
  who:string,
  contacts:string,
  trasformoidee:string,
  esperienze:string,
  sloganOne:string,
  sudime:string,
  competenze:string,
  metodi:string,
  obiettivo:string,
  scrivere:string,
  maunapassione:string,
  ognigiorno:string,
  htmlOne:string,
  htmlTwo:string,
  htmlThree:string,
  htmlFour:string
}
